const express = require("express");
const multer = require("multer");
const router = express.Router();
const { getAllStudents, addStudent, studentSignin , attendanceMark,getListOfPresentDays,getImage,attendanceMarkByFace} = require("../controllers/studentControllers");
const upload = multer({ storage: multer.memoryStorage() });
router.get("/all-students", getAllStudents);
router.post("/getImage",getImage);
router.post("/addstudent",upload.single("studentImage"), addStudent);
router.post("/signin", studentSignin);
router.post("/mark-attendance",attendanceMark);
router.post("/mark-attendance-face",upload.single("studentImage"),attendanceMarkByFace);
router.post("/get-all-days",getListOfPresentDays);
module.exports = router;